name: Build and Deploy
on:
    push:
        branches:
            - 'master'
permissions:
    contents: write
jobs:
    build-and-deploy:
        concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@v3

            - name: Create Build Environment
              run: |
                  yarn global add @quasar/cli

            - name: Install
              run: |
                  yarn install

            - name: Build 🔧
              run: |
                  quasar build

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: dist/spa # The folder the action should deploy.
